name: Tests

on:
  push:
    branches:
      - "**"

env:
  ARTIFACT_RELEASE_ARCHIVE_LINK: https://api.github.com/repos/starkware-libs/cairo/actions/artifacts/584777482/zip
  ARTIFACT_RELEASE_ARCHIVE_NAME: cairo.zip
  RELEASE_ARCHIVE_NAME: x86_64-unknown-linux-musl.tar.gz

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install cairo compiler
        run: |
          curl -H "Accept: application/vnd.github+json" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -L -o $ARTIFACT_RELEASE_ARCHIVE_NAME $ARTIFACT_RELEASE_ARCHIVE_LINK
          unzip $ARTIFACT_RELEASE_ARCHIVE_NAME
          tar -xvf $RELEASE_ARCHIVE_NAME
      - name: Check Cairo compiler version and add to path
        run: |
          $(pwd)/cairo/bin/cairo-compile --version
          echo "$(pwd)/cairo/bin" >> $GITHUB_PATH
      - name: Test the code
        run: make test