name: Tests

on: [push, pull_request]

env:
  ARCHIVE_LINK: https://github.com/starkware-libs/cairo/releases/download/v2.0.0/release-x86_64-unknown-linux-musl.tar.gz
  ARCHIVE_NAME: cairo.zip

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install cairo compiler
        run: |
          curl -L -o $ARCHIVE_NAME $ARCHIVE_LINK
          tar -xvf $ARCHIVE_NAME

      - name: Check Cairo compiler version and add to path
        run: |
          $(pwd)/cairo/bin/cairo-compile --version
          echo "$(pwd)/cairo/bin" >> $GITHUB_PATH

      - name: Test the code
        run: cairo-test .